### PR TITLE
Add chapter 9 slides

### PR DESCRIPTION
**Pull request by shivalikasingh95**
Hi @nerdai 

Would be great if you could review this PR. Updated the readme and added slides for chapter 9.

### CODE REVIEW

**Review by nerdai — CHANGES_REQUESTED** [review]
Thanks @shivalikasingh95!

Small requested change, but can we please use a front-cover similar to what we've used for the other slides. (See [here](https://github.com/mlops-discord/dmls-bookclub/blob/main/slides/chapter8-20240601-manifoldminds.pdf) for example).

It will be good to remain consistent here.

**Comment by shivalikasingh95** [comment]
Hey @nerdai , makes sense. I've updated the ppt with a front cover slide similar to what you shared. Let me know if that works or if any other change is required.

**Review by nerdai — APPROVED** [review]
lgtm!

**Comment by nerdai** [comment]
Thanks again @shivalikasingh95 !

**Pull request merged**
